steps:
  - task: AzureCLI@2
    displayName: Get variables
    inputs:
      azureSubscription: fabian.dev.Azure
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: iac
      inlineScript: |
        az staticwebapp secrets list --name chatbot-test --query "properties.apiKey" -o tsv
        echo "##vso[task.setvariable variable=apiKey;issecret=true]$APIKEY"

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/site'
      output_location: ''
      api_location: '/api'
      azure_static_web_apps_api_token: $(apiKey)